# Generated by Django 5.2.1 on 2025-06-03 22:39

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_attribution.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("identity_value", models.CharField(db_index=True, max_length=255)),
                (
                    "tracking_method",
                    models.CharField(
                        choices=[("cookie", "Cookie Based")],
                        db_index=True,
                        default="cookie",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_visit_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "first_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("first_user_agent", models.TextField(blank=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_identities",
                        to="django_attribution.identity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attribution_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Identities",
            },
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("conversion_type", models.CharField(db_index=True, max_length=255)),
                (
                    "conversion_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default=django_attribution.models.get_default_currency,
                        max_length=3,
                    ),
                ),
                ("custom_data", models.JSONField(blank=True, default=dict)),
                ("source_object_id", models.PositiveIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_as_source_object",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="django_attribution.identity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Touchpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("referrer", models.URLField(blank=True, max_length=2048)),
                ("page_title", models.CharField(blank=True, max_length=255)),
                (
                    "utm_source",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("utm_term", models.CharField(blank=True, max_length=255)),
                ("utm_content", models.CharField(blank=True, max_length=255)),
                ("custom_parameters", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="touchpoints",
                        to="django_attribution.identity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["tracking_method", "identity_value"],
                name="django_attr_trackin_a18ecc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["created_at", "tracking_method"],
                name="django_attr_created_fb49e3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="identity",
            unique_together={("tracking_method", "identity_value")},
        ),
        migrations.AddIndex(
            model_name="conversion",
            index=models.Index(
                fields=["identity", "created_at"], name="django_attr_identit_f10e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversion",
            index=models.Index(
                fields=["conversion_type", "created_at"],
                name="django_attr_convers_920361_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversion",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="django_attr_source__9fdd48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touchpoint",
            index=models.Index(
                fields=["identity", "created_at"], name="django_attr_identit_102964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="touchpoint",
            index=models.Index(
                fields=["utm_source", "utm_medium"],
                name="django_attr_utm_sou_f9e901_idx",
            ),
        ),
    ]
