# Generated by Django 5.2.1 on 2025-06-04 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="identity",
            old_name="user",
            new_name="linked_user",
        ),
    ]
