# Generated by Django 5.2.1 on 2025-06-05 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0002_rename_user_identity_linked_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="identity",
            name="django_attr_trackin_a18ecc_idx",
        ),
        migrations.AlterUniqueTogether(
            name="identity",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["tracking_method"], name="django_attr_trackin_d54f3c_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="identity",
            name="identity_value",
        ),
    ]
