# Generated by Django 5.2.1 on 2025-06-05 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_attribution",
            "0003_remove_identity_django_attr_trackin_a18ecc_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identity",
            name="first_ip_address",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="first_user_agent",
        ),
    ]
