# Generated by Django 5.2.1 on 2025-06-05 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_attribution",
            "0005_conversion_updated_at_identity_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identity",
            name="last_visit_at",
        ),
    ]
