# Generated by Django 5.2.1 on 2025-06-08 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0006_remove_identity_last_visit_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="identity",
            name="django_attr_created_fb49e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="identity",
            name="django_attr_trackin_d54f3c_idx",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="tracking_method",
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["created_at"], name="django_attr_created_440cba_idx"
            ),
        ),
    ]
