# Generated by Django 5.2.1 on 2025-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_attribution",
            "0007_remove_identity_django_attr_created_fb49e3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="is_confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
