# Generated by Django 5.2.1 on 2025-06-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_attribution", "0008_conversion_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversion",
            name="is_confirmed",
        ),
        migrations.AlterField(
            model_name="conversion",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversions",
                to="django_attribution.identity",
            ),
        ),
        migrations.AlterField(
            model_name="conversion",
            name="source_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversions_as_source_object",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="conversion",
            name="source_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
