# Generated by Django 5.2.1 on 2025-06-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0009_remove_conversion_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touchpoint",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="touchpoints",
                to="django_attribution.identity",
            ),
        ),
    ]
