# Generated by Django 5.2.1 on 2025-06-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0012_conversion_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="touchpoint",
            name="custom_parameters",
        ),
        migrations.RemoveField(
            model_name="touchpoint",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="touchpoint",
            name="page_title",
        ),
        migrations.RemoveField(
            model_name="touchpoint",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="identity",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
    ]
