# Generated by Django 5.2.1 on 2025-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0013_remove_touchpoint_custom_parameters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touchpoint",
            name="fbclid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="gclid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="igshid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="li_fat_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="msclkid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="ttclid",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="twclid",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
