# Generated by Django 5.2.1 on 2025-06-19 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="identity",
            old_name="user_agent",
            new_name="first_visit_user_agent",
        ),
    ]
