# Generated by Django 5.2.1 on 2025-06-19 20:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import django_attribution.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "django_attribution",
            "0002_rename_user_agent_identity_first_visit_user_agent",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "monetary_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default=django_attribution.models.get_default_currency,
                        max_length=3,
                    ),
                ),
                ("custom_data", models.JSONField(blank=True, default=dict)),
                (
                    "source_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_confirmed", models.BooleanField(default=True)),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="django_attribution.identity",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions_as_source_object",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Conversion",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["identity", "created_at"], name="django_attr_identit_4eb087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["name", "created_at"], name="django_attr_name_de4c61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="django_attr_source__d35389_idx",
            ),
        ),
    ]
