# Generated by Django 5.2.1 on 2025-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0004_remove_identity_first_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
