# Generated by Django 5.2.1 on 2025-06-12 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_attribution", "0010_alter_touchpoint_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="identity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("merged_into__isnull", True)),
                fields=("linked_user",),
                name="unique_canonical_identity_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="identity",
            constraint=models.CheckConstraint(
                check=models.Q(("merged_into", models.F("id")), _negated=True),
                name="prevent_self_merge",
            ),
        ),
    ]
