# Generated by Django 5.2.1 on 2025-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_attribution",
            "0011_identity_unique_canonical_identity_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="is_confirmed",
            field=models.BooleanField(default=True),
        ),
    ]
