# Generated by Django 5.2.1 on 2025-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "django_attribution",
            "0014_touchpoint_fbclid_touchpoint_gclid_touchpoint_igshid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversion",
            name="django_attr_convers_920361_idx",
        ),
        migrations.RenameField(
            model_name="conversion",
            old_name="conversion_type",
            new_name="event",
        ),
        migrations.AddIndex(
            model_name="conversion",
            index=models.Index(
                fields=["event", "created_at"], name="django_attr_event_e2d18c_idx"
            ),
        ),
    ]
