# Generated by Django 5.2.1 on 2025-06-18 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_attribution",
            "0015_remove_conversion_django_attr_convers_920361_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["linked_user", "merged_into", "created_at"],
                name="django_attr_linked__56cc41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="touchpoint",
            index=models.Index(
                fields=["utm_campaign", "utm_source", "created_at"],
                name="django_attr_utm_cam_b95d45_idx",
            ),
        ),
    ]
