name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Python ${{ matrix.python-version }} - Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            django-version: "4.2"

          - python-version: "3.11"
            django-version: "4.2"

          - python-version: "3.12"
            django-version: "5.1"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install hatch
        pip install "Django~=${{ matrix.django-version }}.0"

    - name: Run linting
      if: matrix.python-version == '3.11'
      run: hatch run lint:all

    - name: Run tests
      run: hatch run test-cov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
